# Generated by Django 5.1 on 2024-08-31 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Режиссёр')),
            ],
            options={
                'verbose_name': 'Режиссёр',
                'verbose_name_plural': 'Режиссёры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип медиа')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('trailer', models.URLField(verbose_name='Ссылка на трейлер')),
                ('year', models.IntegerField(verbose_name='Год выхода')),
                ('rating', models.CharField(max_length=5, verbose_name='Рейтинг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='Изображение')),
                ('external_image_url', models.URLField(blank=True, null=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinopoisk.director', verbose_name='Режиссёр')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinopoisk.genre', verbose_name='Жанр')),
                ('media_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kinopoisk.mediatype', verbose_name='Тип медиа')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
